// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "Copy (2) of index.html",
        "revision": "2d4552433786ea2742f97d24b15a0cda"
    },
    {
        "url": "Copy of index.html",
        "revision": "704b643820a12da3c5569001ef2df08d"
    },
    {
        "url": "index.html",
        "revision": "f8b345b78e4ef362452d62514e3db387"
    },
    {
        "url": "linkedin-formatter-backup-2025-09-29.json",
        "revision": "55f20e38f1fc03ddbbedcea7965f222c"
    },
    {
        "url": "manifest.json",
        "revision": "0cc368b38cab335f44f3f0ec6c9bb905"
    },
    {
        "url": "NotoNastaliqUrdu-Bold.ttf",
        "revision": "0204aebe7b41dc5091f28628d427e455"
    },
    {
        "url": "NotoNastaliqUrdu-Medium.ttf",
        "revision": "98d52a2c6f7a8d671f352145d2205c56"
    },
    {
        "url": "NotoNastaliqUrdu-Regular.ttf",
        "revision": "4537f856ebf024967b0314068f623d4d"
    },
    {
        "url": "NotoNastaliqUrdu-SemiBold.ttf",
        "revision": "c01bbd4250a9d3547a7df33f510e3370"
    },
    {
        "url": "offline.html",
        "revision": "8987c4b748db7cbdf5e4c6165507121b"
    },
    {
        "url": "readme.md",
        "revision": "819466aa9027d4df796b3c057af21d22"
    },
    {
        "url": "replacements-Yasin-linkedin-formatter.json",
        "revision": "9fd4c8d9d0c17868935d9328c84530ab"
    },
    {
        "url": "sw.js",
        "revision": "ec803d5e8c96745861e4dd3e472a7850"
    },
    {
        "url": "symbols-Yasin-linkedin-formatter.json",
        "revision": "a2fbf1490c81cb76782938eaf8a35ec6"
    },
    {
        "url": "fonts/NotoNastaliqUrdu-Bold.ttf",
        "revision": "0204aebe7b41dc5091f28628d427e455"
    },
    {
        "url": "fonts/NotoNastaliqUrdu-Medium.ttf",
        "revision": "98d52a2c6f7a8d671f352145d2205c56"
    },
    {
        "url": "fonts/NotoNastaliqUrdu-Regular.ttf",
        "revision": "4537f856ebf024967b0314068f623d4d"
    },
    {
        "url": "fonts/NotoNastaliqUrdu-SemiBold.ttf",
        "revision": "c01bbd4250a9d3547a7df33f510e3370"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}